/ground_control_station:
  ros__parameters:
    vehicle_list:
      vehicle1: 
        vehicle_id: 1  
        vehicle_type: "uav"
        vehicle_description: "UAV vehicle"
      vehicle_2:
        vehicle_id: 2 
        vehicle_type: "uav"
        vehicle_description: "UAV vehicle"
      vehicle_3:
        vehicle_id: 3
        vehicle_type: "fixed_wing"
        vehicle_description: "Fixed wing vehicle"
